version: "3.8"
services:
  userservice:
    build: ./userservice
    environment:
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASS: example
    ports:
      - 3001:3000
    depends_on:
      - mongo
  fashionservice:
    build: ./fashionservice
    ports:
      - 8000:8000
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  libraryservice:
    build: ./libraryservice
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: library
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
